version: '3'

jobs:
  build:
    machine:
      image: ubuntu-2204:edge
    steps:
      - checkout
      - run:
          name: Change owner on project dir (default user = circleci (1001) and docker needs uid 1000)
          command: sudo chown -R 1000:1000 ../project
      - run:
          name: Install PHP dependencies
          command: docker run -u www-data -v $(pwd):/srv/pim -w /srv/pim --rm akeneo/pim-php-dev:8.1 composer --prefer-dist install
      - run:
          name: Create mandatory yarn directories
          command: mkdir -p ~/.cache/yarn ~/.cache/Cypress ~/.composer && sudo chown -R 1000:1000 ~/.cache/yarn ~/.cache/Cypress ~/.composer
      - run:
          name: Launch the PIM in dev mode
          command: make
          environment:
              YARN_REGISTRY: "http://registry.yarnpkg.com"
      - run:
          name: Test login page HTTP status
          command: curl -f http://localhost:8080/
      - run:
          name: Shutdown dev mode
          command: make down
      - run:
          name: Launch the PIM in prod mode
          command: make prod
          environment:
              YARN_REGISTRY: "http://registry.yarnpkg.com"
      - run:
          name: Test login page HTTP status
          command: curl -f http://localhost:8080/

workflows:
version: '3'
    pull_request:
        jobs:
            - build

    nightly:
        when:
            and:
                - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
                - equal: [ "nightly_v7", << pipeline.schedule.name >> ]
        jobs:
            - build
