name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for Akeneo PIM Node
      run: docker build . --file images/php/Dockerfile --tag intarmour/akeneo-pim-php:$(date +%s)
