name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for Akeneo PIM Node
      run: docker build . --file Dockerfile-node --tag intarmour/akeneo-pim-node:$(date +%s)
    - name: Build the Docker image for Akeneo PIM PHP
      run: docker build . --file Dockerfile-php --tag intarmour/akeneo-pim-php:$(date +%s)
